#!/bin/bash
sudo yum -y update

mkdir ~/downloads
mkdir ~/tls

# install required software git, terraform, atlantis
sudo yum -y install git
wget -O ~/downloads/terraform.zip https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
wget -O ~/downloads/atlantis.zip https://github.com/runatlantis/atlantis/releases/download/v0.12.0/atlantis_linux_386.zip
sudo unzip -o ~/downloads/terraform.zip -d /usr/local/bin/
sudo unzip -o ~/downloads/atlantis.zip -d /usr/local/bin/

sudo openssl genrsa -out ~/tls/tls.key 2048
sudo openssl req -new -x509 -key ~/tls/tls.key -out ~/tls/tls.cert -days 360 -subj /CN=${domain_name}
sudo chmod 0600 ~/tls/tls.key
sudo chmod 0600 ~/tls/tls.cert

# set env variables required for proper work of atlantis
#
# URL - domain name to atlantis service, construct with dns load balancer's name and suffix
# <protocol>://<domain.name>/<suffix>
# protocol: http/https
# suffix: /events
# e.g. http://tf-atlantis-alb-1688671419.eu-west-2.elb.amazonaws.com/events
#
# USERNAME - github account, read from aws secrets manager
#
# TOKEN - github access token, read from aws secrets manager
# access scope: repo:status, repo_deployment, repo_public, admin: read:repo_hook, admin: write:repo_hook
# https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
#
# SECRET - webhook secret, random string
# generated by modules/security/secret module
#
# REPO_WHITELIST - path to repository
# <domain.name>/<github_username>/<project_name>
# e.g. github.com/runatlantis/atlantis
export URL=${url}
export USERNAME=${username}
export TOKEN=${token}
export SECRET=${webhook_secret}
export REPO_WHITELIST=${repo_whitelist}

# run atlantis service in background, log activity to /tmp/atlantis-server.log
atlantis server \
--atlantis-url="$URL" \
--ssl-cert-file=/root/tls/tls.cert \
--ssl-key-file=/root/tls/tls.key \
--gh-user="$USERNAME" \
--gh-token="$TOKEN" \
--gh-webhook-secret="$SECRET" \
--repo-whitelist="$REPO_WHITELIST" \
--log-level="debug" &> /tmp/atlantis-server.log &

# clean sources
sudo rm -rf ~/downloads/
sudo yum -y clean all
sudo rm -rf /var/cache/yum
